### ISSUE TITLE
Checkout failed with windows

### ISSUE THREAD

**Issue by Leopoldine-LolCat** [ctfs/write-ups-2015#362]
Checkout failed on my computer with windows because a special char is used for a folder.

Here is the error :
"fatal: cannot create directory at 'camp-ctf-2015/web/trolol-150/challs.campctf.ccc.ac:10119': Invalid argument"
Can't create a folder with a ":"

Thx,
Best regards.

**Comment by tomvangoethem** [comment]
Should work now :)

**Comment by Leopoldine-LolCat** [comment]
Thanks for this fix !
Checkout almost works now. Few errors for windows still exist :

error: unable to create file defcon-qualifier-ctf-2015/web/waiting-for-your-touch/waiting-for-your-touch.quals.shallweplayaga.me/assets/bootstrap/glyphicons-halflings-regular-a26394f7ede100ca118eff2eda08596275a9839b959c226e15439557a5a80742.woff (No such file or directory)
error: unable to create file defcon-qualifier-ctf-2015/web/waiting-for-your-touch/waiting-for-your-touch.quals.shallweplayaga.me/assets/bootstrap/glyphicons-halflings-regular-fe185d11a49676890d47bb783312a0cda5a44c4039214094e7957b4c040ef11c.woff2 (No such file or directory)

error: unable to create file mma-ctf-2015/web/bow-tickets-500/bow.chal.mmactf.link/~bow/fonts/glyphicons-halflings-regular.eot? (Invalid argument)

error: unable to create file mma-ctf-2015/web/mortal-magi-agents-300/magiagents.chal.mmactf.link/fonts/glyphicons-halflings-regular.eot? (Invalid argument)
error: unable to create file mma-ctf-2015/web/mortal-magi-agents-300/magiagents.chal.mmactf.link/index.html?page=home (Invalid argument)

error: unable to create file mma-ctf-2015/web/mortal-magi-agents-300/magiagents.chal.mmactf.link/index.html?page=news (Invalid argument)
error: unable to create file mma-ctf-2015/web/mortal-magi-agents-300/magiagents.chal.mmactf.link/index.php?page=home (Invalid argument)
error: unable to create file mma-ctf-2015/web/mortal-magi-agents-300/magiagents.chal.mmactf.link/index.php?page=news (Invalid argument)

Can't figure out the error for the 2 firsts.
For the others, it's the forbidden char "?" on windows.

Thanks,
Best regards.

**Comment by tomvangoethem** [comment]
Could it be that the complete path of the first two files is too long?

From <https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx>:

> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters

Could you check that, so I can fix all issues at once?

**Comment by Leopoldine-LolCat** [comment]
Yes !
It was exactly that. Complete path was > 260 chars.
I'll try to checkout in a different path, a folder in C:\ and i didn't have these 2 first errors.

**Comment by tomvangoethem** [comment]
Can you give it another try? Max path length is now 138.

**Comment by Leopoldine-LolCat** [comment]
Thanks !
Now, all works perfectly : )

**Comment by dhanvi** [comment]
If it works perfectly then it time to close the issue :stuck_out_tongue_winking_eye:
